version: '3.8'

services:
  web:
    build:
      context: ../
      dockerfile: dev_tools/Dockerfile
    image: web
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    depends_on:
      - db

  db:
    image: "postgres:alpine"
    
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  alembic:
    build: 
      context: ../
      dockerfile: dev_tools/Dockerfile
    command: alembic upgrade head
    depends_on:
      - db


volumes:
  postgres_data:
